services:
  - type: worker
    name: bot-online-deaths
    env: python
    startCommand: python main.py

  - type: worker
    name: bot-level-monitor
    env: python
    startCommand: python level_monitor_main.py
